{{- if .Values.ingress.enabled }}
{{- $webSvcPort := ternary (.Values.web.sidecars.nginx.port | int) (.Values.web.port | int) .Values.web.sidecars.nginx.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mypick-nijigasaki.fullname" . }}
  labels:
    {{- include "mypick-nijigasaki.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.web }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mypick-nijigasaki.fullname" . }}-web
                port:
                  number: {{ $webSvcPort }}
{{- end }}
